ALTER FUNCTION  KiemTraMonHocDaThi
	(@MAMH NCHAR(5), @LAN INT, @MALOP NCHAR(8))
	RETURNS NCHAR(5)
AS
BEGIN
DECLARE @RESULT NCHAR(5)
SET @RESULT = ''
IF EXISTS (SELECT * FROM SINHVIEN , 
			(SELECT DISTINCT GV.MALOP, GV.MAMH, GV.LAN, BANGDIEM.MASV FROM 
				(SELECT * FROM GIAOVIEN_DANGKY WHERE @MALOP = MALOP) GV INNER JOIN  BANGDIEM ON 
					(BANGDIEM.LAN = GV.LAN AND BANGDIEM.NGAYTHI = GV.NGAYTHI AND BANGDIEM.MAMH = GV.MAMH AND BANGDIEM.MAMH = @MAMH AND BANGDIEM.LAN = @LAN AND BANGDIEM.LAN = GV.LAN)) GVIEN
						WHERE GVIEN.MALOP = SINHVIEN.MALOP AND SINHVIEN.MASV = GVIEN.MASV)
BEGIN
	SET @RESULT = 'X'
END

RETURN @RESULT 
END

SELECT dbo.KiemTraMonHocDaThi('AVCB', 1)