CREATE PROC SP_KTTrinhDo
	@MAMH NCHAR(8), 
	@MALOP NCHAR(8),
	@LAN SMALLINT, 
	@TRINHDO NCHAR(1)
AS
DECLARE @RESULT INT
SET @RESULT = 0
IF EXISTS (SELECT * FROM GIAOVIEN_DANGKY WHERE @MAMH = MAMH AND @MALOP = MALOP AND @LAN = LAN AND @TRINHDO = TRINHDO)
BEGIN
	SET @RESULT = 1
END
SELECT @RESULT AS 'RESULT'

EXEC SP_KTTrinhDo 'AVCB', 'TH04', 1, 'B'