CREATE PROCEDURE [dbo].[SP_KiemTraKhoaTonTai]  
    @MAKH NCHAR(8)
AS  
BEGIN  
DECLARE @Result INT
SET @RESULT = 0

IF EXISTS (SELECT MAKH FROM KHOA WHERE @MAKH = MAKH)
BEGIN
	SET @RESULT = 1
END
ELSE IF EXISTS (SELECT MAKH FROM LINK1.TRACNGHIEM.dbo.KHOA WHERE @MAKH = MAKH)
BEGIN
	SET @RESULT = 1
END

SELECT @Result AS 'Result'  
END  