CREATE PROCEDURE [dbo].[SP_KiemTraGVTonTai]  
    @MAGV NCHAR(8)
AS  
BEGIN  
DECLARE @Result INT
SET @RESULT = 0
IF EXISTS (SELECT MAGV FROM GIAOVIEN WHERE @MAGV = MAGV)
BEGIN
	SET @RESULT = 1
END
SELECT @Result AS 'Result'  
END  