CREATE PROC [dbo].[SP_KiemTraTenLopTonTai]
	@TENLOP NVARCHAR(40)
AS
BEGIN
DECLARE @RESULT INT
SET @RESULT = 0
IF EXISTS (SELECT TENLOP FROM LOP WHERE TENLOP = @TENLOP)
BEGIN
	SET @RESULT = 1
END

ELSE 
	IF EXISTS(SELECT TENLOP from  LINK2.TRACNGHIEM.dbo.LOP  where TENLOP = @TENLOP)
	BEGIN
		SET @RESULT = 1
	END
SELECT @RESULT AS 'RESULT'
END 