CREATE PROC SP_KTSVThuocLop
	@MASV NCHAR(8), 
	@MALOP NCHAR(8)
AS
DECLARE @RESULT INT
SET @RESULT = 0
IF EXISTS (SELECT MALOP FROM SINHVIEN WHERE @MASV = MASV AND @MALOP = MALOP)
BEGIN
	SET @RESULT = 1
END
SELECT @RESULT AS 'RESULT'

