CREATE PROC [dbo].[SP_KiemTraSVTonTai]
	@MASV NCHAR(8)
AS
BEGIN
DECLARE @RESULT INT
SET @RESULT = 0
IF EXISTS (SELECT MASV FROM SINHVIEN WHERE MASV = @MASV)
BEGIN
	SET @RESULT = 1
END

ELSE 
	IF EXISTS(SELECT MASV FROM  LINK2.TRACNGHIEM.dbo.SINHVIEN WHERE MASV = @MASV)
	BEGIN
		SET @RESULT = 1
	END
SELECT @RESULT AS 'RESULT'
END 