ALTER PROC SP_KiemTraDaThi
	@MASV NCHAR(8),
	@MAMH NCHAR(5),
	@LAN SMALLINT
AS
BEGIN
DECLARE @RESULT INT, @MABD INT
SET @RESULT = 0

SELECT @MABD = MABD FROM BANGDIEM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN
IF @MABD IS NOT NULL
BEGIN
	SET @RESULT = 1
END

SELECT @RESULT AS 'RESULT', @MABD AS 'MABD'
END