CREATE PROC [dbo].[SP_KiemTraDangKy]
	@MAMH NCHAR(5),
	@MALOP NCHAR(8),
	@LAN SMALLINT 
AS
BEGIN
SELECT MAGV, MAMH, MALOP, TRINHDO, NGAYTHI, LAN, SOCAUTHI, THOIGIAN FROM dbo.GIAOVIEN_DANGKY WHERE @MAMH = MAMH AND @MALOP = MALOP AND @LAN = LAN
END
