CREATE PROC [dbo].[SP_KiemTraLopTonTai]
	@MALOP NCHAR(8)
AS
BEGIN
DECLARE @RESULT INT
SET @RESULT = 0
IF EXISTS (SELECT MALOP FROM LOP WHERE MALOP = @MALOP)
BEGIN
	SET @RESULT = 1
END

ELSE 
	IF EXISTS(SELECT MALOP from  LINK2.TRACNGHIEM.dbo.LOP  where MALOP = @MALOP)
	BEGIN
		SET @RESULT = 1
	END
SELECT @RESULT AS 'RESULT'
END 