ALTER PROC SP_KTSoCau
	@TRINHDO NCHAR(1), 
	@MAMH NCHAR(5),
	@SOCAU INT
AS
DECLARE @TRINHDO_THAP NCHAR(1), 
	@RESULT INT,
	@DEM INT,
	@DEM2 INT,
	@DEM3 INT,
	@DEM4 INT

SET @DEM = 0
SET @DEM2 = 0
SET @DEM3 = 0
SET @DEM4 = 0

IF @TRINHDO = 'A' 
BEGIN
	SET @TRINHDO_THAP = 'B'
END
ELSE IF @TRINHDO = 'B' 
BEGIN
	SET @TRINHDO_THAP = 'C'
END

IF @TRINHDO = 'A' OR @TRINHDO = 'B'
BEGIN
	SET @DEM = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )

	IF @DEM >= @SOCAU
		SET @RESULT = 1
	ELSE IF @DEM >= @SOCAU*0.7 --NEU > 70% 
	BEGIN
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )

		IF @DEM2 >= @SOCAU - @DEM
			SET @RESULT = 1
		ELSE --NEU %CAU TRINH DO B < SO % CON LAI 
		BEGIN 
			SET @DEM3 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )

			--XET %TRINHDO A O CO SO KHAC NEU >= THI LAY
			IF @DEM3 >= (@SOCAU - @DEM - @DEM2)
				SET @RESULT = 1 
			ELSE
			BEGIN
				SET @DEM4 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )

				IF @DEM4 >= (@SOCAU - @DEM - @DEM2 - @DEM3)
					SET @RESULT = 1
				ELSE SET @RESULT = 0
			END
		END
	END

	ELSE --NEU < 70%
	BEGIN
		--DEM TRINHDO CAO O CO SO KHAC
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA))) 

		IF @DEM2 >= (@SOCAU - @DEM) 
			SET @RESULT = 1
		ELSE IF @DEM2 >= @SOCAU*0.7 - @DEM --NEU TRINH DO A O 2 CO SO CONG LAI >= 70%
		BEGIN
			--DEM TRINHDO THAP O CO SO HIEN TAI
			SET @DEM3 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA))) 

			IF @DEM3 >= (@SOCAU - @DEM - @DEM2) -- NEU SOCAU TRINHDO B >= SO CON LAI THI LAY 2 CAI
				SET @RESULT = 1
			ELSE -- NEU B O CO SO BAN DAU KHONG DU
			BEGIN
				SET @DEM4 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA))) 

				IF @DEM4 >= (@SOCAU - @DEM - @DEM2 - @DEM3) 
					SET @RESULT = 1
				ELSE SET @RESULT = 0
			END
		END

		ELSE SET @RESULT = 0
	END
END

ELSE --TRINH DO C
BEGIN
	SET @DEM = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )

	IF @DEM >= @SOCAU --NEU DU C
		SET @RESULT = 1
	ELSE --NEU THIEU	
	BEGIN
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )
				
		IF @DEM2 >= @SOCAU - @DEM --NEU %C TRONG PHAN MANH KIA >= CON LAI
			SET @RESULT = 1
		ELSE SET @RESULT = 0
	END
END

SELECT @RESULT AS 'RESULT'

EXEC SP_KTSoCau 'A', 'CSDL', 10