CREATE PROCEDURE [dbo].[SP_KiemTraTenKhoaTonTai]  
    @TENKH NVARCHAR(40)
AS  
BEGIN  
DECLARE @Result INT
SET @RESULT = 0

IF EXISTS (SELECT TENKH FROM KHOA WHERE @TENKH = TENKH)
BEGIN
	SET @RESULT = 1
END
ELSE IF EXISTS (SELECT TENKH FROM LINK1.TRACNGHIEM.dbo.KHOA WHERE @TENKH = TENKH)
BEGIN
	SET @RESULT = 1
END

SELECT @Result AS 'Result'  
END  