ALTER PROC [dbo].[SP_ThongTinSV]
@MASV NVARCHAR (50)
AS

DECLARE @MALOP NCHAR(8),
	@TENLOP NVARCHAR(40)

SELECT @MALOP = MALOP FROM SINHVIEN WHERE MASV = @MASV
SELECT @TENLOP = TENLOP FROM LOP WHERE MALOP = @MALOP

SELECT @MALOP AS 'MALOP' , @TENLOP AS 'TENLOP'