ALTER PROCEDURE [dbo].[SP_TimKiemTenMH]  
    @TENMH NVARCHAR(40)
AS  
BEGIN  
DECLARE @Result INT
SET @RESULT = 0
IF EXISTS (SELECT TENMH FROM MONHOC WHERE TENMH = @TENMH)
BEGIN
	SET @RESULT = 1
END

ELSE 
	IF EXISTS(SELECT TENMH FROM  LINK1.TRACNGHIEM.dbo.MONHOC  WHERE TENMH = @TENMH)
	BEGIN
		SET @RESULT = 1
	END
SELECT @Result AS 'Result'  
END  