ALTER PROCEDURE [dbo].[SP_TimKiemMH]  
    @MAMH NCHAR(5)
AS  
BEGIN  
DECLARE @Result INT
SET @RESULT = 0
IF EXISTS (SELECT MAMH FROM MONHOC WHERE MAMH = @MAMH)
BEGIN
	SET @RESULT = 1
END
SELECT @Result AS 'Result'  
END  