CREATE PROCEDURE [dbo].[SP_TimKiemMaBoDe]  
    @CAUHOI INT
AS  
BEGIN  
DECLARE @Result INT
SET @RESULT = 0
IF EXISTS (SELECT CAUHOI FROM BODE WHERE CAUHOI = @CAUHOI)
BEGIN
	SET @RESULT = 1
END
SELECT @Result AS 'Result'  
END  

EXEC SP_TimKiemMaBoDe 1