ALTER PROC [dbo].[SP_ThongTinXemKQ]
	@MAMH NCHAR(5),
	@MALOP NCHAR(8),
	@MABD INT
AS
SELECT NGAYTHI, GIAOVIEN_DANGKY.LAN FROM GIAOVIEN_DANGKY, 
	(SELECT LAN FROM BANGDIEM WHERE MABD = @MABD) BD
	WHERE BD.LAN = GIAOVIEN_DANGKY.LAN AND GIAOVIEN_DANGKY.MALOP=@MALOP AND GIAOVIEN_DANGKY.MAMH=@MAMH
