ALTER PROC SP_XemDSDangKy
	@TUNGAY DATETIME, 
	@DENNGAY DATETIME
AS
SELECT DISTINCT LOP.TENLOP, MONHOC.TENMH, HOTENGV = GIAOVIEN.HO + ' ' +GIAOVIEN.TEN, SOCAUTHI, CONVERT(DATE, NGAYTHI) AS NGAYTHI , dbo.KiemTraMonHocDaThi(GV.MAMH, GV.LAN, GV.MALOP) AS DATHI 
FROM GIAOVIEN_DANGKY GV
	INNER JOIN LOP ON (LOP.MALOP = GV.MALOP)
	INNER JOIN MONHOC ON (MONHOC.MAMH = GV.MAMH)
	INNER JOIN GIAOVIEN ON (GIAOVIEN.MAGV = GV.MAGV)
	
WHERE NGAYTHI <= @DENNGAY AND NGAYTHI >= @TUNGAY ORDER BY NGAYTHI

EXEC dbo.SP_XemDSDangKy '2019-11-27', '2019-12-30'
SELECT dbo.KiemTraMonHocDaThi('AVCB', 2)