CREATE PROC SP_XemBangDiem
	@MALOP NCHAR(8),
	@MAMH NCHAR(5),
	@LAN SMALLINT

AS
BEGIN
	SELECT DISTINCT BANGDIEM.MASV, HOTEN = SINHVIEN.HO + ' ' + SINHVIEN.TEN, DIEM, dbo.XuatDiemChu(DIEM) AS DIEMCHU FROM BANGDIEM INNER JOIN SINHVIEN ON (SINHVIEN.MALOP = @MALOP)
	WHERE BANGDIEM.MAMH = @MAMH AND BANGDIEM.LAN = @LAN AND BANGDIEM.MASV = SINHVIEN.MASV
END

EXEC SP_XemBangDiem 'TH04', 'AVCB', 1