ALTER PROC [dbo].[SP_XemKetQua]
	@MABD INT
AS
SELECT CAUHOI, NOIDUNG, A, B, C, D, DAP_AN, TRALOI FROM CHITIET_BAITHI WHERE MABD = @MABD


--	@MALOP NCHAR(8),
--	@MASV NCHAR(8),
--	@MAMH NCHAR(5)
--AS
--SELECT CAUHOI, NOIDUNG, A, B, C, D, DAP_AN, TRALOI
--	FROM (SELECT GV.LAN, BD.MASV, BD.MAMH
--			FROM (SELECT * FROM GIAOVIEN_DANGKY WHERE MALOP=@MALOP AND MAMH=@MAMH) GV 
--				JOIN (SELECT * FROM BANGDIEM WHERE MAMH=@MAMH AND MASV=@MASV) BD
--					ON GV.MAMH = BD.MAMH AND GV.LAN = BD.LAN AND GV.NGAYTHI = BD.NGAYTHI) TT 
--						JOIN CHITIET_BAITHI CTBT
--							ON (SELECT MABD FROM BANGDIEM 
--								WHERE TT.LAN = LAN AND TT.MASV = MASV AND TT.MAMH = MAMH) = CTBT.MABD 
