DECLARE @TRINHDO NCHAR(1), 
	@TRINHDO_THAP NCHAR(1), 
	@RESULT INT,
	@MALOP NCHAR(8),
	@MAMH NCHAR(5),
	@SOCAU INT,
	@DEM INT,
	@DEM2 INT,
	@DEM3 INT,
	@DEM4 INT

SET @TRINHDO = 'B' 
SET @MAMH = 'CSDL' 
SET @SOCAU = 10
SET @DEM = 0
SET @DEM2 = 0
SET @DEM3 = 0
SET @DEM4 = 0
SET @RESULT = 1

IF @TRINHDO = 'A' 
BEGIN
	SET @TRINHDO_THAP = 'B'
END
ELSE IF @TRINHDO = 'B' 
BEGIN
	SET @TRINHDO_THAP = 'C'
END

CREATE TABLE #TAM (
    CAUHOI INT,
	MAMH NCHAR(5),
	TRINHDO NCHAR(1),
	NOIDUNG NTEXT,
	A NTEXT,
	B NTEXT,
	C NTEXT,
	D NTEXT,
	DAP_AN NCHAR(1),
	MAGV NCHAR(8)
);

IF @TRINHDO = 'A' OR @TRINHDO = 'B'
BEGIN
	SET @DEM = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )

	IF @DEM >= @SOCAU
	BEGIN
		INSERT INTO #TAM SELECT TOP (@SOCAU) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
	END
	
	ELSE IF @DEM >= @SOCAU*0.7 --NEU > 70% 
	BEGIN
	--THEM A VAO BANG TAM TRUOC
		INSERT INTO #TAM SELECT TOP (@DEM) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )

		IF @DEM2 >= @SOCAU - @DEM
		BEGIN
			INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		END

		ELSE --NEU %CAU TRINH DO B < SO % CON LAI 
		BEGIN 
			INSERT INTO #TAM SELECT TOP (@DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

			SET @DEM3 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )

			--XET %TRINHDO A O CO SO KHAC NEU >= THI LAY
			IF @DEM3 >= (@SOCAU - @DEM - @DEM2)
			BEGIN
				INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM - @DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			END

			ELSE
			BEGIN
				INSERT INTO #TAM SELECT TOP (@DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

				SET @DEM4 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )

				IF @DEM4 >= (@SOCAU - @DEM - @DEM2 - @DEM3)
				BEGIN
					INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM - @DEM2 - @DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				END

				ELSE RAISERROR('Khong du cau thi' ,16,1)
			END
		END
	END

	ELSE --NEU < 70%
	BEGIN
		INSERT INTO #TAM SELECT TOP (@DEM) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		
		--DEM TRINHDO CAO O CO SO KHAC
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA))) 

		IF @DEM2 >= (@SOCAU - @DEM) 
		BEGIN
			INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		END

		ELSE IF @DEM2 >= @SOCAU*0.7 - @DEM --NEU TRINH DO A O 2 CO SO CONG LAI >= 70%
		BEGIN
			INSERT INTO #TAM SELECT TOP (@DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

			--DEM TRINHDO THAP O CO SO HIEN TAI
			SET @DEM3 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA))) 

			IF @DEM3 >= (@SOCAU - @DEM - @DEM2) -- NEU SOCAU TRINHDO B >= SO CON LAI THI LAY 2 CAI
			BEGIN
				INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM - @DEM2) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			END

			ELSE -- NEU B O CO SO BAN DAU KHONG DU
			BEGIN
				INSERT INTO #TAM SELECT TOP (@DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

				SET @DEM4 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA))) 

				IF @DEM4 >= (@SOCAU - @DEM - @DEM2 - @DEM3) 
				BEGIN
					INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM - @DEM2 - @DEM3) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				END

				ELSE RAISERROR('Khong du cau thi' ,16,1)
			END
		END

		ELSE RAISERROR('Khong du cau thi' ,16,1)
	END
END

ELSE --TRINH DO C
BEGIN
	SET @DEM = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )

	IF @DEM >= @SOCAU --NEU DU C
	BEGIN
		INSERT INTO #TAM SELECT TOP (@SOCAU) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 
	END

	ELSE --NEU THIEU	
	BEGIN
		INSERT INTO #TAM SELECT TOP (@DEM) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 

		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )
				
		IF @DEM2 >= @SOCAU - @DEM --NEU %C TRONG PHAN MANH KIA >= CON LAI
		BEGIN
			INSERT INTO #TAM SELECT TOP (@SOCAU - @DEM) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 
		END

		ELSE RAISERROR('Khong du cau thi' ,16,1)
	END
END

SELECT * FROM #TAM

DROP TABLE dbo.#TAM
