DECLARE @TRINHDO NCHAR(1), 
	@TRINHDO_THAP NCHAR(1), 
	@RESULT INT,
	@MALOP NCHAR(8),
	@MAMH NCHAR(5),
	@SOCAU INT,
	@DEM INT,
	@DEM2 INT,
	@DEM3 INT,
	@DEM4 INT,
	@PHANTRAM INT,
	@PHANTRAM2 INT,
	@PHANTRAM3 INT,
	@PHANTRAM4 INT

SET @TRINHDO = 'B' 
SET @MAMH = 'CSDL ' 
SET @SOCAU = 10
SET @DEM = 0
SET @DEM2 = 0
SET @DEM3 = 0
SET @DEM4 = 0
SET @PHANTRAM = 0
SET @PHANTRAM2 = 0
SET @PHANTRAM3 = 0
SET @PHANTRAM4 = 0
SET @RESULT = 1

-- DIEU KIEN GIAO VIEN
		--NEU = 'A'
IF @TRINHDO = 'A' 
BEGIN
	SET @TRINHDO_THAP = 'B'
END
ELSE IF @TRINHDO = 'B' 
BEGIN
	SET @TRINHDO_THAP = 'C'
END

CREATE TABLE #TAM (
    CAUHOI INT,
	MAMH NCHAR(5),
	TRINHDO NCHAR(1),
	NOIDUNG NTEXT,
	A NTEXT,
	B NTEXT,
	C NTEXT,
	D NTEXT,
	DAP_AN NCHAR(1),
	MAGV NCHAR(8)
);

--SELECT COUNT(CAUHOI) FROM BODE 
--		WHERE MAMH = @maMH AND TRINHDO = @trinhDo AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA))

----------------------------------------------------------------------------------------------------------
--SELECT TOP (10) * INTO #TAM FROM dbo.BODE 
--	WHERE TRINHDO = 'A' AND MAMH = 'AVCB' AND MAGV IN 
--		(SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()


--INSERT INTO #TAM
--SELECT * FROM BODE WHERE BODE.CAUHOI = 14

--SELECT * FROM #TAM

--DROP TABLE dbo.#TAM

--SELECT ROUND(55.46, 0) --LAM TRON XUONG - DUOI 5 LAY XUONG
--SELECT ROUND(44.54, 0) --LAM TRON LEN- TRÊN 5 LẤY LÊN

--SELECT TOP (ROUND(10*20/100, 0)) * FROM dbo.BODE WHERE TRINHDO = 'A' AND MAMH = 'AVCB' ORDER BY NEWID()


-----------------------------------------------------------------------------------------------------------


IF @TRINHDO = 'A' OR @TRINHDO = 'B'
BEGIN
	SET @DEM = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )
	SET @PHANTRAM = ROUND(CAST(@DEM AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

	IF @PHANTRAM >= 100
	BEGIN
		INSERT INTO #TAM SELECT TOP (@SOCAU) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() -- IN && NOT IN nhan ban: ...INTO # TAM -> INSERT INTO 
	END
	
	ELSE IF @PHANTRAM >= 70 --NEU > 70% 
	BEGIN
	--THEM A VAO BANG TAM TRUOC
		INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )
		SET @PHANTRAM2 = ROUND(CAST(@DEM2 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0)
		
		IF @PHANTRAM2 >= 100 - @PHANTRAM
		BEGIN
			INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM2/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		END

		ELSE --NEU %CAU TRINH DO B < SO % CON LAI 
		BEGIN 
			INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM2/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

			SET @DEM3 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )
			SET @PHANTRAM3 = ROUND(CAST(@DEM3 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

			--XET %TRINHDO A O CO SO KHAC NEU >= THI LAY, K THI XET B
			IF @PHANTRAM3 >= (100 - @PHANTRAM - @PHANTRAM2)
			BEGIN
				INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM3/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			END

			ELSE --XET B
			BEGIN
				INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM3/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

				SET @DEM4 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )
				SET @PHANTRAM4 = ROUND(CAST(@DEM4 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

				IF @PHANTRAM4 >= (100 - @PHANTRAM - @PHANTRAM2 - @PHANTRAM3)
				BEGIN
					INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM4/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				END

				ELSE RAISERROR('Khong du cau thi' ,16,1)
			END
		END
	END

	ELSE --NEU < 70%
	BEGIN
		INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		
		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA))) 
		SET @PHANTRAM2 = ROUND(CAST(@DEM2 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

		IF @PHANTRAM2 >= (100 - @PHANTRAM) -- NEU SOCAU TRINHDO A TRONG CO SO NAY >= SO CON LAI THI LAY 2 CAI
		BEGIN
			INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM2/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
		END

		ELSE IF @PHANTRAM + @PHANTRAM2 >= 70 --NEU TRINH DO A O 2 CO SO CONG LAI >= 70%
		BEGIN
			INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM2/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

			SET @DEM3 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA))) 
			SET @PHANTRAM3 = ROUND(CAST(@DEM3 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

			IF @PHANTRAM3 >= (100 - @PHANTRAM - @PHANTRAM2) -- NEU SOCAU TRINHDO B >= SO CON LAI THI LAY 2 CAI
			BEGIN
				INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM3/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
			END

			ELSE -- NEU B O CO SO BAN DAU KHONG DU
			BEGIN
				INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM3/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()

				SET @DEM4 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA))) 
				SET @PHANTRAM4 = ROUND(CAST(@DEM4 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

				IF @PHANTRAM4 >= (100 - @PHANTRAM - @PHANTRAM2 - @PHANTRAM3) 
				BEGIN
					INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM4/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE WHERE TRINHDO = @TRINHDO_THAP AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID()
				END

				ELSE RAISERROR('Khong du cau thi' ,16,1)
			END
		END

		ELSE RAISERROR('Khong du cau thi' ,16,1)
	END
END

ELSE --TRINH DO C
BEGIN
	SET @DEM = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) )
	SET @PHANTRAM = ROUND(CAST(@DEM AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 

	IF @PHANTRAM >= 100 --NEU DU C
	BEGIN
		INSERT INTO #TAM SELECT TOP (@SOCAU) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 
	END

	ELSE --NEU THIEU	
	BEGIN
		INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 

		SET @DEM2 = (SELECT COUNT (*) FROM BODE WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) )
		SET @PHANTRAM2 = ROUND(CAST(@DEM2 AS FLOAT)/CAST(@SOCAU AS FLOAT)* 100, 0) 
				
		IF @PHANTRAM2 >= 100 - @PHANTRAM --NEU %C TRONG PHAN MANH KIA >= CON LAI
		BEGIN
			INSERT INTO #TAM SELECT TOP (ROUND(@SOCAU*@PHANTRAM2/100, 0)) CAUHOI, MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAP_AN, MAGV FROM dbo.BODE  WHERE TRINHDO = @TRINHDO AND MAMH = @MAMH AND MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH NOT IN (SELECT MAKH FROM KHOA)) ORDER BY NEWID() 
		END

		ELSE RAISERROR('Khong du cau thi' ,16,1)
	END
END

SELECT * FROM #TAM

DROP TABLE dbo.#TAM
