ALTER VIEW [dbo].[V_DSGVChuaCoTaiKhoan]
AS
SELECT MAGV, HOTEN = HO + ' ' + TEN
FROM GIAOVIEN WHERE GIAOVIEN.MAGV IN (SELECT MAGV FROM GIAOVIEN WHERE MAKH IN (SELECT MAKH FROM KHOA))
EXCEPT (SELECT MAGV,  GIAOVIEN.HO + ' ' + GIAOVIEN.TEN 
	FROM GIAOVIEN, (SELECT NAME FROM sys.sysusers , GIAOVIEN WHERE NAME = GIAOVIEN.MAGV) GV 
	WHERE GIAOVIEN.MAGV = GV.NAME)