using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CSDLPT
{
    public partial class frmMonHoc : Form
    {
        int vitri;
        public frmMonHoc()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void mONHOCBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();
            this.bdsMonHoc.EndEdit();
            this.tableAdapterManager.UpdateAll(this.DS);
        }

        private void frmMonHoc_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dS.MONHOC' table. You can move, or remove it, as needed.

            //this.mONHOCTableAdapter.Connection.ConnectionString = Program.connstr;
            this.mONHOCTableAdapter.Fill(this.DS.MONHOC);
        }


        private void btnThem_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //vitri = bdsMonHoc.Position;
            //bdsMonHoc.AddNew();

            panelControl1.Enabled = true; //bat cai panel
            gcMonHoc.Enabled = false;
            //barbtRefesh.Enabled = barbtAdd.Enabled = barbtDel.Enabled = barbtEdit.Enabled = false;
            //barbtSave.Enabled = true;
            this.bdsMonHoc.RemoveFilter(); //xoa bo loc dk lien ket voi bindingsource
            this.bdsMonHoc.AddNew(); //Them mot muc moi vao danh sach
            //((DataRowView)bdsMonHoc[bdsMonHoc.Position])["XOA"] = 0;
            txtMAMH.Focus(); //dieu khien con tro toi o textbox
            //Program.Control = "Add";
        }

       
 


        private void gcMonhoc_Click_1(object sender, EventArgs e)
        {

        }

        private void btnSua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void mAMHTextEdit_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void mAMHLabel_Click(object sender, EventArgs e)
        {

        }


        private void btnThoat_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }
    }
}
